### ISSUE TITLE
Promotion of endpoints to a common type?

### ISSUE THREAD

**Issue by jverzani** [stevengj/HCubature.jl#20]
I was a bit surprised that this failed:

```
 hcubature(x -> 2.0, (0,0), (2pi, pi))
```

(Forcing `pi` to a float through `1pi` works, or course.)

Something similar happens with ` hcubature(x -> 2.0, (0,0), (2, 2.0))`. Would there be any drawbacks to promoting the endpoints to a common type? I see this "T is a floating-point type determined by promoting the endpoint a and b coordinates to a floating-point type" in the README, which suggests that should happen, right?

**Comment by stevengj** [comment]
It already [does do promotion](https://github.com/stevengj/HCubature.jl/blob/master/src/HCubature.jl#L126), but I must have missed something?

**Comment by jverzani** [comment]
It comes from dispatch, as

```
julia> isa((pi, 2pi), NTuple{2,<:Real}) # n = 2
false
```

Not sure you want to relax that. Please close this issue if not.

**Comment by stevengj** [comment]
Ah, I see.  I guess we could replace the current `NTuple` method with something like:
```jl
hcubature_(f, a::Tuple, b::Tuple, norm, rtol, atol, maxevals, initdiv) =
    hcubature_(f, SVector(a), SVector(b), norm, rtol, atol, maxevals, initdiv)
```
since it looks like the `SVector(::Tuple)` constructor knows how to do promotion.

**Comment by jverzani** [comment]
Very nice, thanks!
