### ISSUE TITLE
Add function hquadrature?

### ISSUE THREAD

**Issue by xiaoweiz** [stevengj/HCubature.jl#3]

**Comment by stevengj** [comment]
Okay, added (though you can also call `quadgk` from the QuadGK package.)

**Comment by giordano** [comment]
Would make sense to merge QuadGK and HCubature?

**Comment by stevengj** [comment]
@giordano, I would tend to prefer keeping them separate.  The functionality overlaps (and HCubature calls QuadGK to get 1d coefficients/points), but is not quite the same.  e.g. QuadGK allows one to compute quadrature rules to any order, but HCubature will probably always be fixed-order (or at best limited to a small set of choices).   HCubature requires the integrand to be type stable to gain some extra performance, whereas QuadGK is a bit less picky....

**Comment by stevengj** [comment]
Another way of putting it is that the sharing is mostly one-way.  HCubature gets 1d quadrature rules from QuadGK, but there is not much code in HCubature that would be useful in QuadGK.  (At most a few lines in the `hcubature_` function could be shared.)

**Comment by giordano** [comment]
Point taken, thanks!
